#!/usr/bin/env python3
"""Emit only the reviewed representation metadata; never fetch or rebuild data."""
import argparse
import hashlib
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
POLICY = dict(transform="identity", equality="utf8-byte-exact", cardinality="zero-or-one",
              unmatched="exception", collision="ineligible")
CORE = "982916d73f0a35ff2558b0062f58aa3ac4f24d97"


def encoded(value):
    return (json.dumps(value, ensure_ascii=False, indent=2, sort_keys=True) + "\n").encode("utf-8")


def pinned(path, expected, root=ROOT):
    file = root / path
    if file.is_symlink() or not file.is_file():
        raise ValueError(f"expected regular metadata file: {path}")
    data = file.read_bytes()
    if len(data) > 4 * 1024 * 1024 or hashlib.sha256(data).hexdigest() != expected:
        raise ValueError(f"reviewed metadata changed: {path}")
    return {"path": path, "sha256": expected}


def external(repository, revision, path, sha256):
    return dict(repository="https://github.com/" + repository, revision=revision,
                path=path, sha256=sha256)


def generate(check=False, root=ROOT):
    document = build(root)
    data = encoded(document)
    envelope = encoded(dict(path="model/representations.json", sha256=hashlib.sha256(data).hexdigest()))
    for path, value in [("model/representations.json", data), ("source/representation-attachment.json", envelope)]:
        target = root / path
        if check:
            if target.is_symlink() or not target.is_file() or target.read_bytes() != value:
                raise ValueError(f"generated metadata differs: {path}")
        else:
            if target.is_symlink():
                raise ValueError(f"refusing symbolic output: {path}")
            target.write_bytes(value)
    return document


def build(root=ROOT):
    def local(path, expected):
        return pinned(path, expected, root)


    schema_path = "libs/datatug/main/src/lib/queries/fixtures/public-data-fabric/affiliations.modelspec.json"
    source_revision = "e7362033ec79c6663d7dbe0483b62fab01f7b9cd"
    source = dict(schema=external("datatug/datatug-apps", source_revision, schema_path,
                                  "cfe958f12d9a70bb7533499b76bf01c9447f81f0862852e460b095bb75e1b9cf"),
                  data=external("datatug/datatug-apps", source_revision, schema_path.replace(".modelspec", ""),
                                "44a30dd260c74f43b2138934cca0bccd493c7b804e124c5ecbded3c41226e543"),
                  module="affiliations", entity="Affiliation", property="ror_id", datatype="string", namespace="ROR:URL")
    target = dict(snapshot=local("source/artifact-snapshot.json", "5520cfab8294336fbd98e8c1b4d3f732dffa88249ad58a15743f225cbaf15279"),
                  model=local("model/ror.modelspec.json", "9694a0b6d7aba0bd26be22e8ee3501cf944463617839623e6b5b15d8068fd0ae"),
                  module="ror", entity="organizations", property="id", datatype="string", namespace="ROR:URL",
                  binding=dict(document=local("model/ror.meaning.yaml", "70e54d63b0d564edc73149154f84374cdff30a17b8631c56ecab06dd93d452e9"),
                               concept="research-organization", role="identifier",
                               meaning=dict(document=external("meaninggraph/core", CORE, "identity.meaning.yaml", "b0eb207d1e2e68572a47b4a08d02aa10389e2788c20a9796c812a4fcda894c33"), concept="organization")))
    native = dict(dataset=dict(path="ror.sqlite", sha256="afdf978130ee9899fedb698f0e9d18399efdea40ea92f01f26d6055ef1ed5d38"),
                  provenance=local("source/validation.json", "06aa20ec30551b5eeeca02acdec95da3ebcfdd92524e3048e9d9f6a47d00c6fe"))
    decision = dict(document=external("datatug/datatug", "17263dbacabdfe95e53fc3c6980177416bdab941",
                                    "spec/research/public-data-fabric/evidence/w1-ror-user-decision.json",
                                    "a4caa4b6461230a3fa2ae8548121344cb286cfb98a9e19761a207c9f74479595"),
                    scope="w1-ror-user-native-url")
    return dict(format="ovdb-representation-contract/3", contracts=[dict(execution="native-identifier",
                source=source, target=target, native=native, policy=POLICY, decision=decision)])


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="compare generated bytes without writing")
    args = parser.parse_args()
    try:
        generate(args.check)
    except (ValueError, OSError, KeyError) as error:
        parser.exit(1, f"{error}\n")
    print("Representation metadata reproduced; semantic/canonical admission remains separate.")
